# -*- coding: utf-8 -*-
"""Pokemon Win Prediction Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OXIXtdl1pwo4AXF01jrfMWiouIR_gGv0
"""

!pip install pandas --quiet
!pip install numpy --quiet
!pip install scipy --quiet
!pip install matplotlib --quiet
!pip install seaborn --quiet

import pandas as pd
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
from xgboost import XGBRegressor

from google.colab import files
files.upload()

df1 = pd.read_csv('pokemon.csv')
df2 = pd.read_csv('combats.csv')
merged_df = pd.merge(df2, df1, left_on='First_pokemon', right_on='#', how='left')

merged_df.head()

df = merged_df

df['Type 2'] = df['Type 2'].fillna('None')
df.loc[(df['#'] == 62) & (df['Name'].isna()), 'Name'] = 'Primeape'

df[df['Name'].isnull()]
df.loc[df['#'] == 62, 'Name'] = 'Primeape'
df['Name'] = df['Name'].fillna('Unknown')

df.head()

battles = pd.concat([
    df['First_pokemon'],
    df['Second_pokemon']
]).value_counts()

wins = df['Winner'].value_counts()

win_stats = pd.DataFrame({
    'Battles': battles,
    'Wins': wins
}).fillna(0)

win_stats['Win_Percentage'] = (
    win_stats['Wins'] / win_stats['Battles']
) * 100

win_stats.head()

df.columns

pokemon_with_win_stats = pd.merge(df1, win_stats, left_on='#', right_index=True, how='left')
display(pokemon_with_win_stats.head())

selected_columns = ['HP', 'Attack', 'Speed', 'Win_Percentage']
correlation_matrix = pokemon_with_win_stats[selected_columns].corr()
display(correlation_matrix)

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Pokemon Stats and Win Percentage')
plt.show()

sns.pairplot(pokemon_with_win_stats[selected_columns])
plt.suptitle('Pair Plot of Pokemon Stats vs. Win Percentage', y=1.02)
plt.show()

pokemon_with_win_stats.head(10)['Name']

"""## Split Data into Training and Testing Sets"""

# Fill any NaN values in 'Win_Percentage' with 0 before defining features and target
pokemon_with_win_stats['Win_Percentage'] = pokemon_with_win_stats['Win_Percentage'].fillna(0)

# Define features (X) and target (y)
X = pokemon_with_win_stats[['HP', 'Attack', 'Speed']]
y = pokemon_with_win_stats['Win_Percentage']

# Split the data into training and testing sets (80/20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""## Model Training and Evaluation

### 1. Linear Regression
"""

# Initialize and train the Linear Regression model
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_linear = linear_model.predict(X_test)

# Evaluate the model
mse_linear = mean_squared_error(y_test, y_pred_linear)
r2_linear = r2_score(y_test, y_pred_linear)

print(f"Linear Regression - Mean Squared Error: {mse_linear:.2f}")
print(f"Linear Regression - R-squared: {r2_linear:.2f}")

"""### 2. XGBoost Regressor"""

# Initialize and train the XGBoost Regressor model
xgboost_model = XGBRegressor(random_state=42)
xgboost_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_xgboost = xgboost_model.predict(X_test)

# Evaluate the model
mse_xgboost = mean_squared_error(y_test, y_pred_xgboost)
r2_xgboost = r2_score(y_test, y_pred_xgboost)

print(f"XGBoost Regressor - Mean Squared Error: {mse_xgboost:.2f}")
print(f"XGBoost Regressor - R-squared: {r2_xgboost:.2f}")

"""### 3. Random Forest Regressor"""

# Initialize and train the Random Forest Regressor model
random_forest_model = RandomForestRegressor(random_state=42)
random_forest_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_forest = random_forest_model.predict(X_test)

# Evaluate the model
mse_forest = mean_squared_error(y_test, y_pred_forest)
r2_forest = r2_score(y_test, y_pred_forest)

print(f"Random Forest Regressor - Mean Squared Error: {mse_forest:.2f}")
print(f"Random Forest Regressor - R-squared: {r2_forest:.2f}")

"""## Model Comparison using Mean Absolute Error (MAE)"""

from sklearn.metrics import mean_absolute_error

# Calculate MAE for Linear Regression
mae_linear = mean_absolute_error(y_test, y_pred_linear)
print(f"Linear Regression - Mean Absolute Error: {mae_linear:.2f}")

# Calculate MAE for XGBoost Regressor
mae_xgboost = mean_absolute_error(y_test, y_pred_xgboost)
print(f"XGBoost Regressor - Mean Absolute Error: {mae_xgboost:.2f}")

# Calculate MAE for Random Forest Regressor
mae_forest = mean_absolute_error(y_test, y_pred_forest)
print(f"Random Forest Regressor - Mean Absolute Error: {mae_forest:.2f}")