# -*- coding: utf-8 -*-
"""Heart_Disease_mini_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wteY7-WLMjoxnzwC9zx2Y__FluU0xQ7
"""

# !pip install pandas
# !pip install numpy
# !pip install scipy
# !pip instal matplotlib
# !pip install seaborn

from google.colab import files
files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    log_loss
)

df = pd.read_csv('heart_disease_uci.csv')

num_cols = [
    'age',
    'trestbps',
    'chol',
    'thalch',
    'oldpeak'
]

cat_cols = [
    'sex',
    'dataset',
    'cp',
    'fbs',
    'restecg',
    'exang',
    'slope'
]

scale = StandardScaler()
df[num_cols] = scale.fit_transform(df[num_cols])

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

for col in cat_cols:
    df[col] = df[col].fillna('Unknown')

# df.head()
df.info()
# df.describe()
# df.isnull().sum()
df.isnull().mean() * 100

# df = df.drop('ca', axis=1)
# df = df.drop('thal', axis=1)
# df = df.drop('id', axis=1)
# df['slope'] = df['slope'].fillna('unkown')

X = df.drop('num', axis=1)
y = df['num']

X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X.dtypes

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

acc_score = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Specify 'average' for multiclass classification metrics
prec = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted') # Renamed to avoid conflict with function name
f1 = f1_score(y_test, y_pred, average='weighted') # Renamed to avoid conflict with function name

print(f"Accuracy Score: {acc_score}")
print(f"Precision Score: {prec}")
print(f"Recall Score: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{class_report}")

