# -*- coding: utf-8 -*-
"""Copy of Exercises_XP_Student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B819bcS82YjwdhEckfV-N8tzifuJGISH

# Exercises XP: Introduction to LLMs

Use this guided notebook to follow the platform instructions step by step. Prefilled cells are ready to run; cells containing **TODO** markers need your input.

## 👩‍🏫👩🏿‍🏫 What you’ll learn
- Understand what Large Language Models (LLMs) can do.
- Review the Transformer architecture and the tokenization pipeline.
- Differentiate between pretraining and fine-tuning.
- Generate text with a pretrained language model.

## 🛠️ What you will create
- Markdown answers describing key NLP concepts.
- Python code that loads GPT-2 (or a similar causal LM) and performs basic tokenization and generation.

> **Learning point**
> Work through the exercises sequentially. Run installation cells only once, then focus on filling each TODO before executing the corresponding code.

## 🌟 Exercise 1 · What are Large Language Models?

### 1.1 Define LLMs
TODO: Explain in your own words what LLMs are and what kinds of tasks they are designed to solve.

Large Language Models (LLMs) are artificial intelligence models trained on enormous amounts of text data. During training, they learn patterns, relationships, and language structure by adjusting billions of parameters. This enables them to understand and generate human-like text. LLMs are designed to perform a wide range of language tasks, including answering questions, generating and summarizing text, translating languages, rewriting or editing content, and assisting with coding and other natural language processing tasks.

### 1.2 Prefilled · install core libraries
Run once to install `transformers`, `torch`, and supporting utilities exactly as in the enoncé.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --quiet transformers matplotlib --upgrade

"""### 1.3 Load GPT for causal text generation
Reuse the snippet from the platform: declare the model name, tokenizer, and model weights.

"""

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

model_name = "distilgpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

if None in (model_name, tokenizer, model):
    raise ValueError("Fill in model_name, tokenizer, and model before continuing.")

print(f"\nModel '{model_name}' loaded successfully!")
print("""
GPT-2 is a causal language model, meaning it predicts the next word in a sequence.
It has been trained on a diverse dataset and can generate coherent, contextually relevant text.
""")

"""## 🌟 Exercise 2 · Transformer Architecture and Tokenization

TODO: Describe the tokenization process in your own words before coding.
"""

text = 'I like to eat pizza but I also love steak.'
if text is None:
    raise ValueError("Define the variable `text` with a short sentence.")

tokens = tokenizer.tokenize(text)
token_ids = tokenizer.convert_tokens_to_ids(tokens)

print(f"Original Text: {text}")
print(f"Tokens: {tokens}")
print(f"Token IDs: {token_ids}")

x_label = "Tokens"
y_label = "Token IDs"
title = "Tokenization of Input Text"

if None in (x_label, y_label, title):
    raise ValueError("Set x_label, y_label, and title before plotting.")

plt.figure(figsize=(10, 4))
plt.bar(tokens, token_ids, color="skyblue")
plt.xlabel(x_label)
plt.ylabel(y_label)
plt.title(title)
plt.xticks(rotation=45)
plt.show()

"""## 🌟 Exercise 3 · Token IDs and special prefixes

"""

if 'tokens' not in globals() or 'token_ids' not in globals():
    raise ValueError("Run Exercise 2 to define `tokens` and `token_ids` first.")

# TODO: print the token along with its numeric id
# raise NotImplementedError("Iterate over `tokens` and `token_ids`, printing each mapping.")
# Print each token along with its numeric ID
for token, token_id in zip(tokens, token_ids):
    print(f"{token}: {token_id}")

"""TODO: In plain language, explain what the `Ġ` prefix indicates in GPT-style vocabularies.

## 🌟 Exercise 4 · Generate simple text

Create a fresh prompt, run the generator, and observe how the model extends your sentence token by token.
"""

generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device=0 if torch.cuda.is_available() else -1,
)

input_text = "I enjoy eating pizza because"  # TODO: write a brand-new prompt
if input_text is None:
    raise ValueError("Set `input_text` before generating.")

gen_kwargs = {
    "max_new_tokens": 60,  # TODO: adjust if you want longer/shorter outputs
    "temperature": 0.8,    # TODO: tune sampling temperature
    "top_p": 0.95,
    "do_sample": True,
}

output_ids = generator(input_text, **gen_kwargs)  # TODO: call the generator
output_text = output_ids[0]["generated_text"]     # TODO: extract the text string

print(f"Input: {input_text}")
print(f"Generated Output: {output_text}")

"""> **Learning point**
> Compare the generated continuation with your expectations. Which knobs (temperature, max tokens) change the style the most?

Here's a summary that can help you decide of how to fix these parameters:

![image.png](https://github.com/user-attachments/assets/a4c444d7-fab8-4f56-b7c7-00a15900cb5a)
"""