# -*- coding: utf-8 -*-
"""DailyChallenge_W10_D2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqJclX6cziN1g6CRRp7ZXWvorGFaQhfz
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import mnist

# checking versions
print("tensorflow version", tf.__version__)
print("numpy version", np.__version__)

# loading data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# normalizing the image pixel values to 0-1
X_train = X_train.astype("float32") / 255
X_test = X_test.astype("float32") / 255

# converting labels into O.H.E. format
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# splitting the data set
print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

import matplotlib.pyplot as plt

# Convert one-hot encoded labels back to integer labels
y_train_labels = np.argmax(y_train, axis=1)

# Display the first 10 training images with their labels
plt.figure(figsize=(10, 5))
for i in range(10):
    plt.subplot(2, 5, i + 1) # Arrange in 2 rows, 5 columns
    plt.imshow(X_train[i], cmap='gray')
    plt.title(f"Label: {y_train_labels[i]}")
    plt.axis('off')
plt.tight_layout()
plt.show()

# defining sequential model
model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])
model.summary()

# compiling model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# training the NN
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

cm = tf.math.confusion_matrix(labels=y_true_labels, predictions=y_pred_classes)
cm

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for plotting
metrics_melted = metrics_df.melt(id_vars='Digit', var_name='Metric', value_name='Score')

plt.figure(figsize=(12, 7))
sns.barplot(x='Digit', y='Score', hue='Metric', data=metrics_melted, palette='viridis')
plt.title('Precision and Recall Scores per Digit')
plt.xlabel('Digit')
plt.ylabel('Score')
plt.ylim(0.9, 1.0) # Set a relevant y-axis range to highlight differences
plt.legend(title='Metric')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()