# -*- coding: utf-8 -*-
"""Copy of DailyChallenge-StatforML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YflSpe79Fd9qH_IqKKGHrmz_nSGXsV12

# Daily Challenge - Statistics for Machine Learning

# Applying Inferential Statistics

### Here are the hypotheses to test:
1. Age of people who left the bank and who did not are similar. Alternative: Not similar.
2. Credit score of people who left the bank and who did not are similar. Alternative: Not similar.
3. Balance of people who left the bank and who did not are similar. Alternative: Not similar.
4. Estimated Salary of people who left the bank and who did not are similar. Alternative: Not similar.

#### The most appropriate test to analyse data here is Frequentist test.
"""

!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install scipy
!pip install seaborn

## TODO : load the csv file from this link : https://www.kaggle.com/code/vaibhagarwal/inferential-statistics/input
# from google.colab import files
# uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import scipy.stats
from scipy.stats import ttest_ind
from scipy.special import stdtr
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from numpy.random import seed
import seaborn as sns

# %matplotlib inline
from matplotlib import rcParams
sns.set_style("whitegrid")
sns.set_context("poster")

matplotlib.rcParams['figure.figsize'] = (8.0, 5.0)

## TODO : make into a dataframe called df
df = pd.read_csv('Churn_Modelling.csv')

## TODO : output the first 5 lines
df.head()

## TODO : Create two separate DataFrames, `df_0` and `df_1`, to filter customers who have not exited (0) and customers who have exited (1), respectively
df_0 = df[df['Exited'] == 0]
df_1 = df[df['Exited'] == 1]

"""## Hypothesis 1: Age"""

## TODO: Plot the age distribution for customers who stayed with the bank and those who left using seaborn, with different colors for each group and a legend.
age = df['Age']

sns.histplot(data=df, x='Age', hue='Exited', bins=25, kde=True)

plt.xlabel('Age')
plt.ylabel('Count')
plt.title('Age Distribution by Customer Churn')
plt.show()

## TODO: Calculate the mean and standard deviation of the age for customers who stayed with the bank.
age_mean_0 = df_0['Age'].mean()
age_std_0 = df_0['Age'].std()

## TODO: Calculate the mean and standard deviation of the age for customers who left the bank.
age_mean_1 = df_1['Age'].mean()
age_std_1 = df_1['Age'].std()

## TODO: Perform a t-test to compare the ages of customers who stayed and left the bank.
age_ttest, age_pvalue = ttest_ind(df_0['Age'], df_1['Age'])
print(f"t-statistic: {age_ttest}, p-value: {age_pvalue}")

"""### Using Bootstrapping"""

## TODO: Write a function to perform bootstrap sampling and calculate the statistic of interest.
def bs_choice(data, func, size):
    bs_s = np.empty(size)

    for i in range(size):
        bs_abc = np.random.choice(data, size=len(data), replace=True)
        bs_s[i] = func(bs_abc)

    return bs_s

## TODO: Calculate the difference in means and shift the ages to the overall mean.
age_diff = age_mean_0 - age_mean_1
age_shifted = df['Age'] - age_diff

## TODO: Perform bootstrap sampling to calculate the standard deviation for both groups and their difference.

age_bs_0 = bs_choice(df_0['Age'], np.mean, 1000)
age_bs_1 = bs_choice(df_1['Age'], np.mean, 1000)

## TODO: Calculate the p-value by comparing the difference in means to the bootstrap distribution.
bs_diffs = age_bs_0 - age_bs_1

observed_diff = age_mean_0 - age_mean_1

p_value = np.mean(np.abs(bs_diffs) >= np.abs(observed_diff))

print(p_value)

"""### Conclusion
Do we reject the Null Hypothesis ? Why ?

No. Our Significance Level in this test is 0.05 so with a p-value of 0.499, we do not have enough statistically significant evidence to observe the data. In this case we will reject the null hypothesis.

## Hypothesis 2: Credit Score
"""

## TODO: Create histograms for the CreditScore distribution of both groups (Still with bank and Left the bank).

sns.histplot(data=df, x='CreditScore', hue='Exited', bins=25, kde=True)

plt.xlabel('Credit Score')
plt.ylabel('Count')
plt.title('Credit Score Distribution by Customer Churn')
plt.show()

## TODO: Perform a t-test to compare the CreditScore between the two groups (Still with bank and Left the bank).

credit_score_ttest, credit_score_pvalue = ttest_ind(df_0['CreditScore'], df_1['CreditScore'])

print(f"t-statistic: {credit_score_ttest}, p-value: {credit_score_pvalue}")

"""### Conclusion
Do we reject the Null Hypothesis ? Why ?

Yes. Our Significance Level in this test is 0.05 so with a p-value of 0.006, we have enough statistically significant evidence to reject the null hypothesis.

## Hypothesis 3: Balance
"""

## TODO: Plot the distribution of Balance for both groups (Still with bank and Left the bank).

sns.histplot(data=df, x='Balance', hue='Exited', bins=25, kde=True)

plt.xlabel('Balance')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.title('Balance Distribution by Customer Churn')
plt.show()

## TODO: Perform a t-test to compare the Balance between customers who stayed with the bank and those who left.
balance_ttest, balance_pvalue = ttest_ind(df_0['Balance'], df_1['Balance'])
print(f"t-statistic: {balance_ttest}, p-value: {balance_pvalue}")

## TODO: Visualize the distribution of Balance for customers who stayed with the bank and those who left, excluding zero balances.
sns.histplot(data=df, x='Balance', hue='Exited', bins=25, kde=True)

plt.xlabel('Balance')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.title('Balance Distribution by Customer Churn')

## TODO: Perform a t-test to compare the Balance between customers who stayed with the bank and those who left, excluding zero balances.
balance_ttest, balance_pvalue = ttest_ind(df_0['Balance'], df_1['Balance'])
print(f"t-statistic: {balance_ttest}, p-value: {balance_pvalue}")

"""## Conclusion

Do we reject the Null Hypothesis ? Why ?

Yes. Our Significance Level in this test is 0.05 so with a p-value of 1.2755633191525477e-32, we have enough statistically significant evidence to reject the null hypothesis.

## Hypothesis 4: Estimated Salary
"""

## TODO: Plot the distribution of EstimatedSalary for customers who stayed with the bank and those who left.
sns.histplot(data=df, x='EstimatedSalary', hue='Exited', bins=25, kde=True)

plt.xlabel('Estimated Salary')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.title('Estimated Salary Distribution by Customer Churn')
plt.show()

## TODO: Perform a t-test to compare the EstimatedSalary between customers who stayed and those who left.
salary_ttest, salary_pvalue = ttest_ind(df_0['EstimatedSalary'], df_1['EstimatedSalary'])
print(f"t-statistic: {salary_ttest}, p-value: {salary_pvalue}")

"""### Using Bootstrapping"""

## TODO: Calculate the difference in means and shift the EstimatedSalary for both groups.
salary_diff = df_0['EstimatedSalary'].mean() - df_1['EstimatedSalary'].mean()
salary_shifted = df['EstimatedSalary'] - salary_diff

## TODO: Calculate the bootstrap sample means for both groups and their difference.
salary_bs_0 = bs_choice(df_0['EstimatedSalary'], np.mean, 1000)
salary_bs_1 = bs_choice(df_1['EstimatedSalary'], np.mean, 1000)

## TODO: Calculate the p-value based on the bootstrap distribution of the difference in means.
bs_diffs = salary_bs_0 - salary_bs_1

observed_diff = df_0['EstimatedSalary'].mean() - df_1['EstimatedSalary'].mean()

p_value = np.mean(np.abs(bs_diffs) >= np.abs(observed_diff))

print(p_value)

"""### Conclusion
Do we reject the Null Hypothesis ? Why ?

No. Our Significance Level in this test is 0.05 so with a p-value of 0.519, we do not have enough statistically significant evidence to observe the data. In this case we will reject the null hypothesis.

## Final Conclusion
What will be the most helpful feature in predicting churning? Credit Score
"""