# -*- coding: utf-8 -*-
"""DailyChallenge_W13_D2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17gN-Nvd9tyd27tqk-niRPbI67dg5ascY
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install peft==0.4.0

!mkdir -p cache # Use -p to avoid error if directory exists

!pip install datasets

from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
foundation_model = AutoModelForCausalLM.from_pretrained(model_name)

# Set pad_token_id to eos_token_id if not set (common for GPT-like models)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

data = load_dataset("Abirate/english_quotes") # Sample 10%
data = data.map(lambda samples: tokenizer(samples["quote"], truncation=True, padding="max_length", max_length=128), batched=True)
train_sample = data["train"].select(range(5))
display(train_sample)

import peft
from peft import LoraConfig, get_peft_model

#Fill in `r=1` and `target_modules`.
lora_config = LoraConfig(
    r=8,
    lora_alpha=16, # a scaling factor that adjusts the magnitude of the weight matrix. Usually set to 1
    target_modules=["c_attn", "c_proj", "c_fc"], # Common for GPT2, adjust based on model architecture
    lora_dropout=0.05,
    bias="none", # this specifies if the bias parameter should be trained.
    task_type="CAUSAL_LM"
)

#Add the adapter layers to the foundation model to be trained
peft_model = get_peft_model(foundation_model, lora_config)
print(peft_model.print_trainable_parameters())


# Fill out the `Trainer` class.

import transformers
from transformers import TrainingArguments, Trainer
import os
import time # Import time for time_now
from datasets import Features, Value # Import Features and Value for explicit schema definition

output_directory = os.path.join("../cache/working", "peft_lab_outputs")
training_args = TrainingArguments(
    report_to="none",
    output_dir=output_directory,
    auto_find_batch_size=True,
    learning_rate= 3e-2, # Higher learning rate than full fine-tuning.
    num_train_epochs=3,
    use_cpu=True # Set to False if using GPU
)

trainer = Trainer(
    model=peft_model,
    args=training_args,
    train_dataset=train_sample,
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

# Ensure train_sample has labels and explicit features for the Trainer
# For causal language modeling, labels are usually the input_ids themselves
# Define the expected features after tokenization and label assignment
expected_features = Features({
    'input_ids': Value('int64'), # Tokenizer typically outputs int64
    'attention_mask': Value('int64'),
    'labels': Value('int64')
})

# Map to add 'labels' column, then cast to enforce the feature schema
train_sample = train_sample.map(
    lambda examples: {'labels': examples['input_ids']},
    batched=True
)
# Cast the dataset to ensure the features are explicitly defined and consistent.
# This will also remove any columns not in expected_features, like the original 'quote'.
train_sample = train_sample.cast(expected_features)

trainer.train()

# Load the PEFT model using pre-defined LoRA configs and foundation model. We set `is_trainable=False` to avoid further training.


time_now = int(time.time())
peft_model_path = os.path.join(output_directory, f"peft_model_{time_now}")
trainer.model.save_pretrained(peft_model_path)

# Generate output tokens

inputs = tokenizer("Two things are infinite: ", return_tensors="pt")
outputs = peft_model.generate(
    input_ids=inputs["input_ids"],
    attention_mask=inputs["attention_mask"],
    max_new_tokens=50,
    num_beams=5, # Use beam search for better quality
    do_sample=True, # Allow sampling
    top_k=50,
    no_repeat_ngram_size=2
    )

print(tokenizer.batch_decode(outputs, skip_special_tokens=True))